# Uncomment the next line to define a global platform for your project
 platform :ios, '15.2'

target 'MVPproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Keychain'
  pod 'SwiftGen'

  # Pods for MVPproject

  target 'MVPproject-Moke' do
    pod 'Keychain'
  end
end

