
name: Recipes
options:
  bundleIdPrefix: com.Recipes
  postGenCommand: pod update
  Debug.Dev: debug
  Debug.Prod: debug
  Release: release
packages:
  TextFileds:
    url: https://github.com/suprunovv/TextFileds
    majorVersion: 1.0.0
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    majorVersion: 2.8.0
targets:
  MVPproject:
    type: application
    platform: iOS
    deploymentTarget: 15.2
    sources:
     - /Users/macbookpro/Desktop/MVP/MVPproject/MVPproject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1.0.0
        IOS_DEPLOYMENT_TARGET: 15.2
        MARKETING_VERSION: 1
        ENABLE_USER_SCRIPT_SANDBOXING: false
            
        INFOPLIST_KEY_UILaunchScreen_Generation: true

        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: TextFileds
      - package: Swinject
    postCompileScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
                    "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
  MVPproject-Moke:
    type: application
    platform: iOS
    deploymentTarget: 15.2
    sources:
     - /Users/macbookpro/Desktop/MVP/MVPproject/MVPproject
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1.0.0
        IOS_DEPLOYMENT_TARGET: 15.2
        MARKETING_VERSION: 1
        ENABLE_USER_SCRIPT_SANDBOXING: false
            
        INFOPLIST_KEY_UILaunchScreen_Generation: true

        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
        GENERATE_INFOPLIST_FILE: true
        
        OTHER_SWIFT_FLAGS: "-D Mock"
    dependencies:
      - package: TextFileds
      - package: Swinject
    postCompileScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
                    "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
  MVPprojectTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 15.2
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: TextFileds
      - package: Swinject

    
       

        
        
  
